# Generated by Django 5.0.6 on 2024-09-19 15:56

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254)),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10)),
                ('telefono', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_materia', models.CharField(max_length=255, verbose_name='Nombre de la Materia')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('1', 'Personaje'), ('2', 'Lugar'), ('3', 'Objeto'), ('4', 'Evento')], max_length=1, verbose_name='Tipo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='entradas/', verbose_name='Imagen')),
                ('contenido', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Contenido')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254)),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10)),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe estar en el formato: '+999999999'. Hasta 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')])),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255, unique=True, verbose_name='Código del Salón')),
                ('grado', models.CharField(max_length=50, verbose_name='Grado')),
                ('seccion', models.CharField(max_length=50, verbose_name='Sección')),
            ],
            options={
                'verbose_name': 'Salón',
                'verbose_name_plural': 'Salones',
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.FloatField(verbose_name='Calificación')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='entradas.alumno', verbose_name='Alumno')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='entradas.asignatura', verbose_name='Asignatura')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
            },
        ),
        migrations.AddField(
            model_name='asignatura',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='entradas.profesor'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesores', to='entradas.salon'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='entradas.salon'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='entradas.salon'),
        ),
    ]
